max_connections=350
shared_buffers=60MB
temp_buffers=1MB
work_mem=1MB
wal_buffers=4MB
checkpoint_timeout=15min
effective_cache_size=512MB
fsync=off
commit_delay=10000
effective_io_concurrency=200
random_page_cost=1.1
synchronous_commit=off
ssl=off
hba_file=/var/db/postgres4/lab2/pg_hba.conf
