# TYPE  DATABASE        USER            ADDRESS                 METHOD


local   all             postgres                                peer
# local   all             all                                     peer
host    all             all             ::/0                    password
host    all             all             0.0.0.0/0               password

local   replication     all                                     peer
host    replication     all             127.0.0.1/32            scram-sha-256
host    replication     all             ::1/128                 scram-sha-256
